// flow-typed signature: dec846208f7ed51ede398b115f70cc0b
// flow-typed version: <<STUB>>/redux-pender_v^1.2.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-pender'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-pender' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-pender/lib/actionTypes' {
  declare module.exports: any;
}

declare module 'redux-pender/lib/applyPenders' {
  declare module.exports: any;
}

declare module 'redux-pender/lib/createPenderAction' {
  declare module.exports: any;
}

declare module 'redux-pender/lib/index' {
  declare module.exports: any;
}

declare module 'redux-pender/lib/middleware' {
  declare module.exports: any;
}

declare module 'redux-pender/lib/pender' {
  declare module.exports: any;
}

declare module 'redux-pender/lib/penderize' {
  declare module.exports: any;
}

declare module 'redux-pender/lib/reducer' {
  declare module.exports: any;
}

declare module 'redux-pender/lib/resetPender' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-pender/lib/actionTypes.js' {
  declare module.exports: $Exports<'redux-pender/lib/actionTypes'>;
}
declare module 'redux-pender/lib/applyPenders.js' {
  declare module.exports: $Exports<'redux-pender/lib/applyPenders'>;
}
declare module 'redux-pender/lib/createPenderAction.js' {
  declare module.exports: $Exports<'redux-pender/lib/createPenderAction'>;
}
declare module 'redux-pender/lib/index.js' {
  declare module.exports: $Exports<'redux-pender/lib/index'>;
}
declare module 'redux-pender/lib/middleware.js' {
  declare module.exports: $Exports<'redux-pender/lib/middleware'>;
}
declare module 'redux-pender/lib/pender.js' {
  declare module.exports: $Exports<'redux-pender/lib/pender'>;
}
declare module 'redux-pender/lib/penderize.js' {
  declare module.exports: $Exports<'redux-pender/lib/penderize'>;
}
declare module 'redux-pender/lib/reducer.js' {
  declare module.exports: $Exports<'redux-pender/lib/reducer'>;
}
declare module 'redux-pender/lib/resetPender.js' {
  declare module.exports: $Exports<'redux-pender/lib/resetPender'>;
}
