// flow-typed signature: 12b666912998c1a1d2271b57b2d9b9ef
// flow-typed version: <<STUB>>/sortablejs_v^1.7.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sortablejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sortablejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sortablejs/Sortable' {
  declare module.exports: any;
}

declare module 'sortablejs/Sortable.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sortablejs/Sortable.js' {
  declare module.exports: $Exports<'sortablejs/Sortable'>;
}
declare module 'sortablejs/Sortable.min.js' {
  declare module.exports: $Exports<'sortablejs/Sortable.min'>;
}
