// flow-typed signature: 6f6eb0c970765e0915d1a426ee94c8bb
// flow-typed version: <<STUB>>/serverless-dotenv-plugin_v^1.0.2/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-dotenv-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-dotenv-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'serverless-dotenv-plugin/index' {
  declare module.exports: $Exports<'serverless-dotenv-plugin'>;
}
declare module 'serverless-dotenv-plugin/index.js' {
  declare module.exports: $Exports<'serverless-dotenv-plugin'>;
}
