service:
  name: jaewoomade-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-2
  stage: dev
  environment:
    SECRET_KEY: ${file(./env.json):SECRET_KEY}
    COCKROACHDB_HOST: ${file(./env.json):COCKROACHDB_HOST}
    COCKROACHDB_PW: ${file(./env.json):COCKROACHDB_PW}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
      - "ses:SendEmail"
      Resource: "*"

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
      - http:
          path: /{any+}
          method: ANY
